package BESA.SocialRobot.ServiceProvider.services;

public enum ServiceNames {
    MAIL, MESSAGE, MOVEMENT,EMOTIONEXTRACTOR,RAWVIDEO,INTERFACEEVENT, SENTIMENTANALYSIS, SPEECHENGINE, ROBOT_RESOURCES
}
